---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
words: “boat,book,vote,seat,backpack,partition,groundhog”
---
server:
  port: 0
---
spring:
  application:
    name: lab-4-noun